/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as CasesCaseIdIndexRouteImport } from './routes/cases.$caseId.index'
import { Route as CasesCaseIdOcrRouteImport } from './routes/cases.$caseId.ocr'
import { Route as CasesCaseIdLogsRouteImport } from './routes/cases.$caseId.logs'
import { Route as CasesCaseIdIntegrityRouteImport } from './routes/cases.$caseId.integrity'
import { Route as CasesCaseIdFinancialRouteImport } from './routes/cases.$caseId.financial'
import { Route as CasesCaseIdEvidenceRouteImport } from './routes/cases.$caseId.evidence'
import { Route as CasesCaseIdDeepfakeRouteImport } from './routes/cases.$caseId.deepfake'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCaseIdIndexRoute = CasesCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdOcrRoute = CasesCaseIdOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdLogsRoute = CasesCaseIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdIntegrityRoute = CasesCaseIdIntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdFinancialRoute = CasesCaseIdFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdEvidenceRoute = CasesCaseIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdDeepfakeRoute = CasesCaseIdDeepfakeRouteImport.update({
  id: '/deepfake',
  path: '/deepfake',
  getParentRoute: () => CasesCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/login': typeof LoginRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/': typeof CasesIndexRoute
  '/cases/$caseId/deepfake': typeof CasesCaseIdDeepfakeRoute
  '/cases/$caseId/evidence': typeof CasesCaseIdEvidenceRoute
  '/cases/$caseId/financial': typeof CasesCaseIdFinancialRoute
  '/cases/$caseId/integrity': typeof CasesCaseIdIntegrityRoute
  '/cases/$caseId/logs': typeof CasesCaseIdLogsRoute
  '/cases/$caseId/ocr': typeof CasesCaseIdOcrRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cases': typeof CasesIndexRoute
  '/cases/$caseId/deepfake': typeof CasesCaseIdDeepfakeRoute
  '/cases/$caseId/evidence': typeof CasesCaseIdEvidenceRoute
  '/cases/$caseId/financial': typeof CasesCaseIdFinancialRoute
  '/cases/$caseId/integrity': typeof CasesCaseIdIntegrityRoute
  '/cases/$caseId/logs': typeof CasesCaseIdLogsRoute
  '/cases/$caseId/ocr': typeof CasesCaseIdOcrRoute
  '/cases/$caseId': typeof CasesCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/login': typeof LoginRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/': typeof CasesIndexRoute
  '/cases/$caseId/deepfake': typeof CasesCaseIdDeepfakeRoute
  '/cases/$caseId/evidence': typeof CasesCaseIdEvidenceRoute
  '/cases/$caseId/financial': typeof CasesCaseIdFinancialRoute
  '/cases/$caseId/integrity': typeof CasesCaseIdIntegrityRoute
  '/cases/$caseId/logs': typeof CasesCaseIdLogsRoute
  '/cases/$caseId/ocr': typeof CasesCaseIdOcrRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/login'
    | '/cases/$caseId'
    | '/cases/'
    | '/cases/$caseId/deepfake'
    | '/cases/$caseId/evidence'
    | '/cases/$caseId/financial'
    | '/cases/$caseId/integrity'
    | '/cases/$caseId/logs'
    | '/cases/$caseId/ocr'
    | '/cases/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cases'
    | '/cases/$caseId/deepfake'
    | '/cases/$caseId/evidence'
    | '/cases/$caseId/financial'
    | '/cases/$caseId/integrity'
    | '/cases/$caseId/logs'
    | '/cases/$caseId/ocr'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/login'
    | '/cases/$caseId'
    | '/cases/'
    | '/cases/$caseId/deepfake'
    | '/cases/$caseId/evidence'
    | '/cases/$caseId/financial'
    | '/cases/$caseId/integrity'
    | '/cases/$caseId/logs'
    | '/cases/$caseId/ocr'
    | '/cases/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$caseId/': {
      id: '/cases/$caseId/'
      path: '/'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof CasesCaseIdIndexRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/ocr': {
      id: '/cases/$caseId/ocr'
      path: '/ocr'
      fullPath: '/cases/$caseId/ocr'
      preLoaderRoute: typeof CasesCaseIdOcrRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/logs': {
      id: '/cases/$caseId/logs'
      path: '/logs'
      fullPath: '/cases/$caseId/logs'
      preLoaderRoute: typeof CasesCaseIdLogsRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/integrity': {
      id: '/cases/$caseId/integrity'
      path: '/integrity'
      fullPath: '/cases/$caseId/integrity'
      preLoaderRoute: typeof CasesCaseIdIntegrityRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/financial': {
      id: '/cases/$caseId/financial'
      path: '/financial'
      fullPath: '/cases/$caseId/financial'
      preLoaderRoute: typeof CasesCaseIdFinancialRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/evidence': {
      id: '/cases/$caseId/evidence'
      path: '/evidence'
      fullPath: '/cases/$caseId/evidence'
      preLoaderRoute: typeof CasesCaseIdEvidenceRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/deepfake': {
      id: '/cases/$caseId/deepfake'
      path: '/deepfake'
      fullPath: '/cases/$caseId/deepfake'
      preLoaderRoute: typeof CasesCaseIdDeepfakeRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
  }
}

interface CasesCaseIdRouteChildren {
  CasesCaseIdDeepfakeRoute: typeof CasesCaseIdDeepfakeRoute
  CasesCaseIdEvidenceRoute: typeof CasesCaseIdEvidenceRoute
  CasesCaseIdFinancialRoute: typeof CasesCaseIdFinancialRoute
  CasesCaseIdIntegrityRoute: typeof CasesCaseIdIntegrityRoute
  CasesCaseIdLogsRoute: typeof CasesCaseIdLogsRoute
  CasesCaseIdOcrRoute: typeof CasesCaseIdOcrRoute
  CasesCaseIdIndexRoute: typeof CasesCaseIdIndexRoute
}

const CasesCaseIdRouteChildren: CasesCaseIdRouteChildren = {
  CasesCaseIdDeepfakeRoute: CasesCaseIdDeepfakeRoute,
  CasesCaseIdEvidenceRoute: CasesCaseIdEvidenceRoute,
  CasesCaseIdFinancialRoute: CasesCaseIdFinancialRoute,
  CasesCaseIdIntegrityRoute: CasesCaseIdIntegrityRoute,
  CasesCaseIdLogsRoute: CasesCaseIdLogsRoute,
  CasesCaseIdOcrRoute: CasesCaseIdOcrRoute,
  CasesCaseIdIndexRoute: CasesCaseIdIndexRoute,
}

const CasesCaseIdRouteWithChildren = CasesCaseIdRoute._addFileChildren(
  CasesCaseIdRouteChildren,
)

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRouteWithChildren
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRouteWithChildren,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
